#!/usr/bin/env bash
# Strategy A: completion scripts copied out of the boxes, one winner per
# command, resolved off the finished index so that dispatch and completion
# can never disagree about which box a command belongs to.
source "$(dirname "${BASH_SOURCE[0]}")/helpers.sh"
setup_sandbox

COMPD="$XDG_CACHE_HOME/sora/completions.d"
OUT="$XDG_DATA_HOME/sora/completions"

make_box_meta alpha 10
make_box_meta beta 20
make_box_list alpha shared onlyalpha
make_box_list beta shared onlybeta

put() { # box kind filename content
    mkdir -p "$COMPD/$1/$2"
    printf '%s\n' "$4" > "$COMPD/$1/$2/$3"
}

put alpha bash shared     '# alpha version'
put beta  bash shared     '# beta version'
put alpha bash onlyalpha  '# alpha only'
put beta  bash onlybeta   '# beta only'
put alpha zsh  _onlyalpha '#compdef onlyalpha'
put beta  fish onlybeta.fish 'complete -c onlybeta'

"$MERGE_BIN" "$XDG_CONFIG_HOME/sora" "$XDG_CACHE_HOME/sora" "$XDG_DATA_HOME/sora"

# 1. Higher priority wins the completion, exactly as it wins the index entry.
assert_eq "$(index_lookup shared)" "beta" "index winner is beta (priority 20)"
assert_contains "$(cat "$OUT/bash/shared")" "beta version" \
    "completion comes from the same box that wins dispatch"

# 2. Commands unique to a box are carried over untouched.
assert_contains "$(cat "$OUT/bash/onlyalpha")" "alpha only" "unique command from alpha"
assert_contains "$(cat "$OUT/bash/onlybeta")" "beta only" "unique command from beta"

# 3. Per-shell naming: zsh wants _cmd, fish wants cmd.fish.
[ -f "$OUT/zsh/_onlyalpha" ] || fail "zsh completion not materialized as _onlyalpha"
[ -f "$OUT/fish/onlybeta.fish" ] || fail "fish completion not materialized as onlybeta.fish"

# 4. A pin must move the completion with the dispatch, or the user gets
#    alpha's flags while running beta's binary.
"$SORA_BIN" pin shared alpha >/dev/null || fail "pin failed"
assert_eq "$(index_lookup shared)" "alpha" "pin moved the index entry"
assert_contains "$(cat "$OUT/bash/shared")" "alpha version" \
    "pin moved the completion too"

# 5. A completion for a command the box no longer provides must disappear.
make_box_list alpha onlyalpha          # 'shared' dropped from alpha
make_box_list beta onlybeta            # 'shared' dropped from beta too
"$SORA_BIN" pin --remove shared >/dev/null || fail "unpin failed"
[ -f "$OUT/bash/shared" ] && fail "stale completion survived for an unindexed command"

# 6. Backwards compatibility: called with two arguments (an in-box script
#    generated by an older sora), it must still build the index and simply
#    not touch the completion tree.
rm -rf "$OUT"
"$MERGE_BIN" "$XDG_CONFIG_HOME/sora" "$XDG_CACHE_HOME/sora"
assert_eq "$(index_lookup onlyalpha)" "alpha" "two-argument call still merges"
[ -d "$OUT" ] && fail "two-argument call must not write the completion tree"

# 7. The generated in-box reindex script must carry the sync step and pass
#    DATA_DIR through to the merge (content is where quoting bugs hide).
tpl=$("$SORA_BIN" _template reindex)
assert_contains "$tpl" "completions.d" "reindex template syncs completions"
assert_contains "$tpl" '"$CONFIG_DIR" "$CACHE_DIR" "$DATA_DIR"' \
    "reindex template passes DATA_DIR to the merge"
assert_contains "$tpl" "index.d/\$BOX.list" \
    "sync filters by the commands the box actually provides"

echo "ok: completion sync"
